{{- range $name, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juraregel-{{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juraregel-{{ $name }}
  template:
    metadata:
      labels:
        app: juraregel-{{ $name }}
    spec:
      containers:
      - name: api
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        command: ["python", "use-cases/{{ $name }}/api/app.py"]
        ports:
        - containerPort: {{ $api.port }}
{{- end }}
{{- end }}
